version: "3.8"

networks:
  backend:
    external: true

services:
  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9334:9001"
      - "9443:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - /home/jsancosta/data/s3_data:/data
    networks:
      - backend

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/typebot;
      /usr/bin/mc anonymous set public minio/typebot/public;
      exit 0;"
    networks:
      - backend

  typebot-builder:
    image: baptistearno/typebot-builder:${SOFTWARE_VERSION_TAG}
    restart: always
    depends_on:
      - postgres
    ports:
      - "8484:3000"
    environment:
      - DATABASE_URL=postgresql://${TYPEBOT_DB_USER}:${TYPEBOT_DB_PASSWORD}@postgres:5432/typebot
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_VIEWER_URL=${NEXT_PUBLIC_VIEWER_URL}
      - DEFAULT_WORKSPACE_PLAN=${DEFAULT_WORKSPACE_PLAN}
      - ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
      - DISABLE_SIGNUP=${DISABLE_SIGNUP}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_AUTH_DISABLED=${SMTP_AUTH_DISABLED}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GOOGLE_AUTH_CLIENT_ID=${GOOGLE_AUTH_CLIENT_ID}
      - GOOGLE_AUTH_CLIENT_SECRET=${GOOGLE_AUTH_CLIENT_SECRET}
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=${ADMIN_PASSWORD}
      - S3_BUCKET=typebot
      - S3_PORT=443
      - S3_ENDPOINT=${MINIO_ENDPOINT}
      - S3_SSL=true
    networks:
      - backend

  typebot-viewer:
    image: baptistearno/typebot-viewer:${SOFTWARE_VERSION_TAG}
    restart: always
    depends_on:
      - postgres
    ports:
      - "8585:3000"
    environment:
      - DATABASE_URL=postgresql://${TYPEBOT_DB_USER}:${TYPEBOT_DB_PASSWORD}@postgres:5432/typebot
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_VIEWER_URL=${NEXT_PUBLIC_VIEWER_URL}
      - ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
    networks:
      - backend
